/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

public class AppTest {

    @Test
    public void testMain() {
        // This is a placeholder test for App.java
        // You can add code here to test App.main() if needed
    }
}
